"""images table

Revision ID: a02d4d8359a7
Revises: abb3fbd2c5e3
Create Date: 2019-09-01 11:39:21.234273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02d4d8359a7'
down_revision = 'abb3fbd2c5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('img', sa.BLOB(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_name'), 'images', ['name'], unique=True)
    op.add_column('boxes', sa.Column('img_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'boxes', 'images', ['img_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'boxes', type_='foreignkey')
    op.drop_column('boxes', 'img_id')
    op.drop_index(op.f('ix_images_name'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
